export const ICONS = {
	INBOX: 'InboxIcon',
	PLUS: 'PlusIcon',
	SUN: 'SunIcon',
	MOON: 'MoonIcon',
	LOADING: 'LoadingIcon',
	NOTE: 'NoteIllustration',
	TASK: 'TaskIllustration',
	CHEVRON_TOP: 'ChevronTopIcon',
	CHEVRON_DOWN: 'ChevronDownIcon',
	ARROW: 'ArrowTwoIcon',
	MINUS: 'MinusIcon',
	DELETE: 'DeleteIcon',
	ALPHABET_TOP: 'AlphabetTopIcon',
	ALPHABET_DOWN: 'AlphabetDownIcon',
	FILTER: 'FilterIcon',
	UPDATE_TOP: 'UpdateTopIcon',
	UPDATE_DOWN: 'UpdateDownIcon',
	TRASH: 'TrashIcon',
	PRIORITY_TOP: 'PriorityTopIcon',
	PRIORITY_DOWN: 'PriorityDownIcon',
	CREATE_TOP: 'CreateTopIcon',
	CREATE_DOWN: 'CreateDownIcon',
	EDIT: 'EditIcon',
	CHECK: 'CheckIcon',
}
